// React/src/orig_App.js
import 'devextreme/dist/css/dx.light.css';
import React from 'react';
import './App.css';

import { DateRangeBox } from 'devextreme-react/date-range-box';

class App extends React.Component {
  startDate = new Date();
  endDate = new Date(new Date().setDate(new Date().getDate() + 7)); 
  minDate = new Date(new Date().setDate(new Date().getDate() - 14));
  maxDate = new Date(new Date().setDate(new Date().getDate() + 14));

  constructor(props) {
    super(props);
    this.valueChanged = this.onValueChanged.bind(this);
  }   
  
  onValueChanged = (e) => {
    console.log(e.previousValue);
    console.log(e.value);
  }  
  
  render() {
    return (
      <div className="App">
        <DateRangeBox
            startDate={this.startDate}
            endDate={this.endDate}
            min={this.minDate}
            max={this.maxDate}
            startDateLabel="Start"
            endDateLabel="End"
            labelMode="floating"
            displayFormat="EEEE, MMM d"
            useMaskBehavior={true}
            showClearButton={true}
            openOnFieldClick={false}
            onValueChanged={this.onValueChanged}
        />
      </div>
    );    
  }

}

export default App;

// Angular/src/app/orig_app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  startDate: Date = new Date();
  endDate: Date = new Date(new Date().setDate(new Date().getDate() + 7)); 
  minDate: Date = new Date(new Date().setDate(new Date().getDate() - 14));
  maxDate: Date = new Date(new Date().setDate(new Date().getDate() + 14));

  valueChanged = (e) => {
    console.log(e.value);
    console.log(e.previousValue);
  }
}
